### ISSUE TITLE
Add copy code feature

### ISSUE THREAD

**Issue by Keith-Web3** [akash-melkeri/loading-animations#21]
The loaders on the site are pretty cool but right now, they don't help much since a user can't get the code to use it in their project.
I suggest we add a feature that lets a user copy the code of a selected animation.

**Comment by akash-melkeri** [comment]
That is great idea. I like it. So want to work on this feature ?

**Comment by Keith-Web3** [comment]
Yes, I do.

**Comment by Keith-Web3** [comment]
Kindly assign the issue to me @akash-melkeri

**Comment by akash-melkeri** [comment]
All set ! 
let me know if you need anything .

**Comment by Keith-Web3** [comment]
> All set ! let me know if you need anything .

Okay

**Comment by Keith-Web3** [comment]
Hello @akash-melkeri. I tried a lot of ways but the best way I found to implement this feature will be for the the styles of each loader to be placed in a json file where it can be fetched from onclick like this 
![Screenshot (30)](https://user-images.githubusercontent.com/96974022/194648089-c7ba073e-97a6-4f9d-b427-c0925ec9a15f.png)
This JSON file just like the html will have a specified format. This would mean a little extra work for the contributors (just copy and paste) but I believe it is well worth it for the benefit of this feature
Should I go ahead with it?

**Comment by akash-melkeri** [comment]
I like the json storing idea. But what I fail to understand is how you will store it in json?
I mean what will be format.
When I gave this problem a thought, I thought of a popup. which will open when copy code btn will be clicked.
that popup will have the code of corresponding loader.

**Comment by akash-melkeri** [comment]
I am just suggesting.
You can use whichever Idea you feel will be better.
Afterall you were the one who suggested it.

**Comment by Keith-Web3** [comment]
> I like the json storing idea. But what I fail to understand is how you will store it in json? I mean what will be format. When I gave this problem a thought, I thought of a popup. which will open when copy code btn will be clicked. that popup will have the code of corresponding loader.

About this, the problem the json file is trying to solve isn't how the styles code will be copied but how it will be gotten. If I get the styles using JavaScript, a lot of irrelevant default styles will also be copied and the user will have to start removing the unnecessary code but with the JSON, the relevant styles can just be fetched from the JSON file and then copied to the user's clipboard.

**Comment by Keith-Web3** [comment]
> I like the json storing idea. But what I fail to understand is how you will store it in json? I mean what will be format. When I gave this problem a thought, I thought of a popup. which will open when copy code btn will be clicked. that popup will have the code of corresponding loader.

The template / format of the JSON file will be like this
![Screenshot (36)](https://user-images.githubusercontent.com/96974022/194711765-ae437861-982c-42ad-a199-926b495bb917.png)
